apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: x-translatethread-com
  namespace: tools
spec:
  secretName: x-translatethread-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - x.translatethread.com
