apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: translatethread-com
  namespace: tools
spec:
  secretName: translatethread-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - translatethread.com
